### PR TITLE
Doesn't render banner if current URL is on whitelist closes #88

### LINKED ISSUE #88: If site is on whitelist, it should not be rendered as blacklisted on the DOM

### PR DESCRIPTION
**Pull request by r3dcrosse**

### CODE REVIEW

**Comment by MistrBrown** [comment]
Use storage functions with getBackgroundPage()

**Comment by r3dcrosse** [comment]
Can't access background page from content script without sending a message. It's easier to pull from sync storage directly from that content script.

**Comment by wattmalsh** [comment]
Hold off on merging this pull request until our standup tomorrow.

**Comment by MistrBrown** [comment]
Roger

**Pull request closed without merging**
